@startuml

title Finish Device

state "STATE_LASER_ADJUSTING" as laser
state "STATE_PEERS_CONNECTING" as connection
state "STATE_REACT_TO_MESSAGE" as react
state "STATE_PROCESS_MESSAGE" as process
state "STATE_CHECK_SENSORS" as check

[*] --> connection
connection --> laser : communication\nestablished
laser --> react : laser ok
react --> process : msg available
process --> check
react --> check : no message
check --> react
check --> laser : laser unavailable
check --> connection : connection lost

@enduml