@startuml

title Start Device

state "STATE_LASER_1_ADJUSTING" as laser
state "STATE_LASER_2_ADJUSTING" as laser2
state "STATE_PEERS_CONNECTING" as connection
state "STATE_READY" as ready
state "STATE_RUN" as run
state "STATE_FINISH" as finish

[*] --> connection
connection --> laser : communication\nestablished
laser --> laser2 : laser1 ok
laser2 --> ready : msg (laser2 ok)
ready --> laser: laser 1 unavailable
ready --> run : laser 1\ninterrupted
ready --> connection : connection lost
run --> finish : msg\n(finish request)
run --> ready : button\npressed
finish --> ready : timeout
finish --> ready : button\npressed

@enduml